# Generated by Django 5.1.5 on 2025-01-27 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalClassification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kingdom_name', models.CharField(max_length=250)),
                ('species', models.CharField(max_length=250)),
                ('number_of_species', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('animal_class', models.CharField(max_length=250)),
                ('order', models.CharField(max_length=250)),
                ('domestic', models.BooleanField(default=False)),
                ('wild_animal', models.BooleanField(default=False)),
                ('credits', models.TextField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('contributors', models.ManyToManyField(blank=True, related_name='animal_classification_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal Classification',
                'verbose_name_plural': 'Animal Classifications',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('areas_in_uganda', models.CharField(max_length=250)),
                ('known_values', models.TextField()),
                ('value_details', models.TextField()),
                ('unique_habitat', models.CharField(max_length=250)),
                ('toxicity_to_humans', models.CharField(max_length=250)),
                ('diet', models.CharField(max_length=250)),
                ('behavior', models.CharField(max_length=250)),
                ('habitat_impact', models.CharField(max_length=250)),
                ('conservation_status', models.CharField(max_length=250)),
                ('conservation_measures', models.CharField(max_length=250)),
                ('reproduction', models.CharField(max_length=250)),
                ('gestation_period', models.CharField(max_length=250)),
                ('life_span', models.CharField(max_length=250)),
                ('predators', models.TextField()),
                ('prey', models.TextField()),
                ('ethical_medicinal_uses', models.TextField()),
                ('threats', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='animal_videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='animal_audios')),
                ('citation', models.TextField()),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('credits', models.TextField(blank=True, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('contributors', models.ManyToManyField(blank=True, related_name='animal_contributions', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalclassification')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('animal', 'Animal'), ('classification', 'Classification')], max_length=50)),
                ('entry_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalLocalName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('local_name', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_names', to='animals.animal')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_name_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal Local Name',
                'verbose_name_plural': 'Animal Local Names',
                'unique_together': {('animal', 'local_name', 'language')},
            },
        ),
    ]
