# Generated by Django 5.1.5 on 2025-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('total_entries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('model_name',)},
            },
        ),
        migrations.DeleteModel(
            name='AnimalEntryCounter',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
