# Generated by Django 5.1.5 on 2025-01-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalEntryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('animal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('areas_in_Uganda', models.CharField(blank=True, max_length=250, null=True)),
                ('known_values', models.TextField(blank=True, null=True)),
                ('value_details', models.TextField(blank=True, null=True)),
                ('unique_habitat', models.CharField(blank=True, max_length=250, null=True)),
                ('toxicity_to_humans', models.CharField(blank=True, max_length=250, null=True)),
                ('diet', models.CharField(blank=True, max_length=250, null=True)),
                ('behavior', models.CharField(blank=True, max_length=250, null=True)),
                ('habitat_impact', models.CharField(blank=True, max_length=250, null=True)),
                ('conservation_status', models.CharField(blank=True, max_length=250, null=True)),
                ('conservation_measures', models.CharField(blank=True, max_length=250, null=True)),
                ('reproduction', models.CharField(blank=True, max_length=250, null=True)),
                ('gestation_period', models.CharField(blank=True, max_length=250, null=True)),
                ('life_span', models.CharField(blank=True, max_length=250, null=True)),
                ('predators', models.TextField(blank=True, null=True)),
                ('prey', models.TextField(blank=True, null=True)),
                ('ethical_medicinal_uses', models.TextField(blank=True, null=True)),
                ('threats', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='animal_videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='animal_audios')),
                ('citation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='contributors',
        ),
        migrations.DeleteModel(
            name='AnimalContributor',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='contributor',
        ),
        migrations.AlterModelOptions(
            name='animalclassification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animallocalname',
            options={},
        ),
        migrations.RenameField(
            model_name='animalclassification',
            old_name='id',
            new_name='animal_classification_id',
        ),
        migrations.RenameField(
            model_name='animallocalname',
            old_name='id',
            new_name='animal_local_name_id',
        ),
        migrations.RemoveField(
            model_name='animalclassification',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='animalclassification',
            name='entry_count',
        ),
        migrations.RemoveField(
            model_name='animallocalname',
            name='entry_count',
        ),
        migrations.AlterField(
            model_name='animalclassification',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_animal_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalclassification',
            name='number_of_species',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='animallocalname',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='Contributor who added this local name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_name_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='animal_classifications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='animals.animalclassification'),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalentrycounter',
            name='animal',
            field=models.OneToOneField(help_text='The animal this counter tracks.', on_delete=django.db.models.deletion.CASCADE, related_name='entry_counter', to='animals.animalprofile'),
        ),
        migrations.AlterField(
            model_name='animallocalname',
            name='animal',
            field=models.ForeignKey(help_text='The animal associated with this local name.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_names', to='animals.animalprofile'),
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
