# Generated by Django 5.1.5 on 2025-02-11 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='animal_classifications',
        ),
        migrations.AlterField(
            model_name='animalprofile',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='animal_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='animal_classifications',
            field=models.ManyToManyField(related_name='animal_profiles', to='animals.animalclassification'),
        ),
    ]
