# Generated by Django 5.1.5 on 2025-02-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_entrycounter_delete_animalentrycounter_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entrycounter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='entrycounter',
            name='model_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
