# Generated by Django 5.1.5 on 2025-01-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animalentrycounter_animalprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalentrycounter',
            old_name='entry_count',
            new_name='total_entries',
        ),
        migrations.RemoveField(
            model_name='animalentrycounter',
            name='animal',
        ),
    ]
