# Generated by Django 5.1.5 on 2025-02-11 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animalprofile_animal_classifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='animal_classifications',
        ),
        migrations.AddField(
            model_name='animalprofile',
            name='animal_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='animals_profiles', to='animals.animalclassification'),
            preserve_default=False,
        ),
    ]
