# Generated by Django 5.1.5 on 2025-02-10 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_rename_date_entered_animalprofile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalclassification',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributed_animal_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
