# Generated by Django 5.1.5 on 2025-01-28 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_rename_entry_count_animalentrycounter_total_entries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='contributor',
            field=models.ForeignKey(blank=True, help_text='Contributor who added ANIMAL PROFILE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ANIMAL_PROFILE_contributOR', to=settings.AUTH_USER_MODEL),
        ),
    ]
