# Generated by Django 5.1.5 on 2025-02-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animalclassification_contributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalprofile',
            old_name='contributors',
            new_name='contributor',
        ),
    ]
