# Generated by Django 5.1.5 on 2025-02-11 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_animalclassification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalprofile',
            name='animal_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalclassification'),
        ),
    ]
