# Generated by Django 5.1.5 on 2025-01-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animalprofile_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='contributor',
        ),
    ]
