# Generated by Django 5.1.5 on 2025-02-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_animalprofile_animal_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalclassification',
            name='domestic',
        ),
        migrations.RemoveField(
            model_name='animalclassification',
            name='wild_animal',
        ),
    ]
