# Generated by Django 5.1.5 on 2025-02-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animalclassification_domestic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalclassification',
            name='contributors',
        ),
    ]
