# Generated by Django 5.1.6 on 2025-02-18 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clans', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CulturalKingdom',
            fields=[
                ('cultural_kingdom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kingdom_name', models.CharField(max_length=250, unique=True)),
                ('title_of_leader', models.CharField(blank=True, choices=[('king', 'King'), ('chief', 'Chief')], max_length=250, null=True)),
                ('number_of_clans', models.IntegerField(default=1, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=250, null=True)),
                ('citation', models.CharField(blank=True, max_length=250, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_kingdoms', to=settings.AUTH_USER_MODEL)),
                ('primary_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_cultural_kingdoms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clan_name', models.CharField(max_length=250, unique=True)),
                ('clan_seat', models.CharField(blank=True, max_length=250)),
                ('clan_anthem', models.TextField(blank=True, null=True)),
                ('clan_roles', models.TextField(blank=True, null=True)),
                ('totem', models.CharField(blank=True, max_length=250)),
                ('secondary_totem', models.CharField(blank=True, max_length=250)),
                ('clan_history', models.TextField(blank=True)),
                ('clan_leader_title', models.CharField(blank=True, max_length=250)),
                ('clan_leader_name', models.CharField(blank=True, max_length=250)),
                ('cultural_sites', models.TextField(blank=True)),
                ('male_names', models.TextField(blank=True)),
                ('female_names', models.TextField(blank=True)),
                ('reserved_male_names', models.TextField(blank=True)),
                ('reserved_female_names', models.TextField(blank=True)),
                ('taboos', models.TextField(blank=True)),
                ('lead_god', models.CharField(blank=True, max_length=250)),
                ('other_gods', models.CharField(blank=True, max_length=250)),
                ('citation', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clans', to=settings.AUTH_USER_MODEL)),
                ('primary_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clans', to=settings.AUTH_USER_MODEL)),
                ('cultural_kingdom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures.culturalkingdom')),
            ],
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('ethnic_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ethnic_group_name', models.CharField(max_length=250, unique=True)),
                ('region_in_Uganda', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_ethnicities', models.IntegerField(blank=True, default=1, null=True)),
                ('number_of_languages', models.IntegerField(default=1, null=True)),
                ('number_of_kingdoms_or_chiefdoms', models.IntegerField(default=1, null=True)),
                ('citation', models.CharField(blank=True, max_length=250, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnic_groups', to=settings.AUTH_USER_MODEL)),
                ('primary_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ethnic_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.clan')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cultural_kingdom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.culturalkingdom')),
                ('ethnic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultures.ethnicgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('ethnicity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ethnicity_name', models.CharField(max_length=250, unique=True)),
                ('region_in_Uganda', models.CharField(blank=True, max_length=250, null=True)),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('common_food_types', models.TextField(blank=True, null=True)),
                ('staple_food', models.CharField(blank=True, max_length=250, null=True)),
                ('main_cash_crop', models.CharField(blank=True, max_length=250, null=True)),
                ('leisure_activities', models.TextField(blank=True, null=True)),
                ('entertainment_activities', models.TextField(blank=True, null=True)),
                ('denominations', models.TextField(blank=True, null=True)),
                ('universal_rituals', models.TextField(blank=True, null=True)),
                ('ceremonies', models.TextField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnicities', to=settings.AUTH_USER_MODEL)),
                ('ethnic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures.ethnicgroup')),
                ('primary_contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ethnicities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='culturalkingdom',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures.ethnicity'),
        ),
        migrations.AddField(
            model_name='clan',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures.ethnicity'),
        ),
    ]
