# Generated by Django 5.1.5 on 2025-02-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ethnicgroup',
            old_name='number_of_ethnicity',
            new_name='number_of_ethnicities',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='ethnicgroup',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='contributors',
        ),
        migrations.AddField(
            model_name='clan',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clanprofile',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='culturalkingdom',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_kingdoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnic_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethnicity',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ethnicities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clan',
            name='primary_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_clans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='citation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='primary_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_cultural_kingdoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='citation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='primary_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ethnic_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='primary_contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_ethnicities', to=settings.AUTH_USER_MODEL),
        ),
    ]
