# Generated by Django 5.1.6 on 2025-02-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_profession_userprofile_proffession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgfuser',
            name='is_contributor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fgfuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
