# Generated by Django 5.1.5 on 2025-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgfuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fgfuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
