# Generated by Django 5.1.6 on 2025-02-18 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantEntryCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlantScientificClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('animal_class', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('synonyms', models.TextField(blank=True, max_length=255, null=True)),
                ('english_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('distribution_in_uganda', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('life_form', models.CharField(choices=[('forest', 'Forest'), ('meadow', 'Meadow'), ('climber', 'Climber'), ('grassland', 'Grassland'), ('herb', 'Herb'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('perennial', 'Perennial'), ('vine', 'Vine'), ('water', 'Water'), ('tender', 'Tender'), ('other', 'Other')], max_length=100, null=True)),
                ('life_span', models.CharField(blank=True, max_length=100, null=True)),
                ('climate_impact', models.CharField(blank=True, max_length=100, null=True)),
                ('threats', models.CharField(blank=True, max_length=100, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=100, null=True)),
                ('conservation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('known_values', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='plant_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='plant_audio/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('citation', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to=settings.AUTH_USER_MODEL)),
                ('plant_scientific_classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.plantscientificclassification')),
            ],
        ),
        migrations.CreateModel(
            name='MedicinalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issues', models.TextField()),
                ('part_used', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_steps', models.TextField()),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('contraindications', models.TextField()),
                ('shelf_life', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cultural_value', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('review_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicinal_plants', to=settings.AUTH_USER_MODEL)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_info', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_gallery', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantVideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='plant_videos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_gallery', to='plants.plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.language')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_names', to='plants.plant')),
            ],
            options={
                'unique_together': {('plant', 'language', 'local_name')},
            },
        ),
    ]
