# Generated by Django 5.1.5 on 2025-02-10 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantentrycounter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plantentrycounter',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='plantimagegallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plantimagegallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='plantlocalname',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plantlocalname',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='plantvideogallery',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plantvideogallery',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='scientificclassification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='scientificclassification',
            name='updated_at',
        ),
    ]
